"""add is_default and preferences columns

Revision ID: 6db7e0d84c40
Revises: ab29e3a05762
Create Date: 2026-01-15 01:33:54.378660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db7e0d84c40'
down_revision: Union[str, None] = 'ab29e3a05762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('profiles', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('profiles', 'is_default')
    # ### end Alembic commands ###
